# Object Oriented Programming

In [2]:
import pandas as pd
import numpy as np
from decimal import Decimal
import copy

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
from car import Car

## objects and classes from python world

### class 'str'

In [7]:
city = "Toulouse" # object of type (class) str
print(city, type(city), sep=": ")

Toulouse: <class 'str'>


In [8]:
# upper is a method of class str
city.upper()

'TOULOUSE'

In [9]:
city.startswith('Tou')

True

In [10]:
city + ', ville rose'

'Toulouse, ville rose'

In [11]:
# TypeError: can only concatenate str (not "int") to str
# city + 2

In [12]:
city * 10

'ToulouseToulouseToulouseToulouseToulouseToulouseToulouseToulouseToulouseToulouse'

### class 'Decimal' and 'float'

In [14]:
price = Decimal('0.1') # constructor
price, 2*price, 3*price

(Decimal('0.1'), Decimal('0.2'), Decimal('0.3'))

In [15]:
type(price)

decimal.Decimal

In [16]:
price_f = 0.1
price_f, 2*price_f, 3*price_f

(0.1, 0.2, 0.30000000000000004)

In [17]:
type(price_f)

float

### numpy: class 'ndarray'

In [19]:
values = np.random.normal(10, 2.5, 10_000)
matrix = np.random.normal(10, 2.5, (10_000, 10_000))

In [20]:
values

array([ 5.47913435, 10.99864746,  6.26537854, ..., 10.94912008,
        9.7959281 , 12.30809599])

In [21]:
for a in values, matrix:
    print(a) # => calls str(a) => calls method ndarray.__str__()
    print("type:", type(a))
    print("shape:", a.shape)
    print("data type:", a.dtype)
    print("data type:", a.flags)
    print("length:", len(a)) # length on 1st dimension => calls method ndarray.__len__()
    print()

[ 5.47913435 10.99864746  6.26537854 ... 10.94912008  9.7959281
 12.30809599]
type: <class 'numpy.ndarray'>
shape: (10000,)
data type: float64
data type:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

length: 10000

[[10.73873066 10.26676359  8.31383291 ... 10.66968177 12.46012279
  13.9499799 ]
 [11.91058727  8.51443896  6.44509166 ... 13.20895857  9.12595564
   8.78404288]
 [10.83996411 10.94594214  7.61152496 ...  6.25664576  9.45327516
  10.43364118]
 ...
 [ 6.39703741 12.06512839  8.04544051 ... 14.30810662  7.88278939
  11.37585419]
 [10.37017773  4.90573251  8.24260694 ...  8.92031836 13.9810413
  10.89756285]
 [12.74034303  7.97736989  9.89782714 ...  9.20256298  8.67768371
  10.16814334]]
type: <class 'numpy.ndarray'>
shape: (10000, 10000)
data type: float64
data type:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

length: 1

In [22]:
matrix.T.flags # owndata = False => view

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [23]:
matrix.sum()

999987862.5494183

In [24]:
matrix.sum(axis=1) # by rows

array([100094.81344445,  99562.7480659 ,  99367.28334841, ...,
       100111.08608853, 100190.44275245,  99962.69853796])

In [25]:
matrix.diagonal()

array([10.73873066,  8.51443896,  7.61152496, ..., 14.30810662,
       13.9810413 , 10.16814334])

In [26]:
# ndarray are iterable
list(values[:10])

[5.479134352607772,
 10.998647458894403,
 6.2653785370862956,
 11.539570206905488,
 7.6145304957524775,
 12.814807188117172,
 13.01165275663101,
 13.721592090343897,
 8.807024793908068,
 12.226121345354848]

In [27]:
values.__iter__

<method-wrapper '__iter__' of numpy.ndarray object at 0x0000024AF981F090>

In [28]:
values[:5] + 1 # calls ndarray.__add__

array([ 6.47913435, 11.99864746,  7.26537854, 12.53957021,  8.6145305 ])

In [29]:
# calls int.__add__ with arg values[:5] => returns NotImplemented
# calls ndarray.__radd__
1 + values[:5] 

array([ 6.47913435, 11.99864746,  7.26537854, 12.53957021,  8.6145305 ])

In [30]:
x = 1
x.__add__(values[:5])

NotImplemented

In [31]:
values[:5].__radd__(1)

array([ 6.47913435, 11.99864746,  7.26537854, 12.53957021,  8.6145305 ])

## custom class 'Car'

In [33]:
Car?

Init signature: Car(model: str, color: str | None = None, power: int | None = None)
Docstring:     
class representing a car with its model, power and color

Example:
    car = Car(model='Fiat 500', color='rose', power=150)
File:           c:\users\matth\documents\formation\python\stage20240722perf\car.py
Type:           type
Subclasses:     

In [34]:
c = Car('Fiat 500') # calls constructor __init__(...)
print(c) # calls str()
c # calls repr()

Fiat 500 (color=None, power=None)


Car(model=Fiat 500, color=None, power=None)

In [35]:
c.model

'Fiat 500'

In [36]:
c.color = 'rose'
c.color

'rose'

In [37]:
# AttributeError: 'Car' object has no attribute 'kilometer'
# c.kilometer
# c.kilometer = 100_000 # ok if no slots else AttributeError: 'Car' object has no attribute 'kilometer'
# c.kilometer

In [38]:
c2 = Car('Super 5')
# AttributeError: 'Car' object has no attribute 'kilometer'
# c2.kilometer

In [39]:
dir(c)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 'color',
 'model',
 'power']

In [40]:
c.__class__ # or type(c)

car.Car

In [41]:
c.__module__

'car'

In [42]:
cars = [
    Car(model="Fiat 500", color="rose", power=150),
    Car(model="Super 5", color="gris", power=65),
    Car(model="Ferrari F40", color="rouge", power=400),
]

In [43]:
# fonction anonyme
# anonymouse function
# lambda function
# Ex:    lambda car: car.power
# en Java: car -> car.power
# en Javascript, C#:   car => car.power
cars.sort(key=lambda car: car.power, reverse=True)
cars

[Car(model=Ferrari F40, color=rouge, power=400),
 Car(model=Fiat 500, color=rose, power=150),
 Car(model=Super 5, color=gris, power=65)]

In [44]:
# TypeError: '<' not supported between instances of 'Car' and 'Car'
# cars.sort()

In [45]:
c = Car(model="Fiat 500", color="rose", power=150)
c in cars

True

In [46]:
print(cars[0])
print(c)
cars[0] == c, cars[0] is c

Ferrari F40 (color=rouge, power=400)
Fiat 500 (color=rose, power=150)


(False, False)

In [47]:
print(cars[1])
print(c)
cars[1] == c, cars[1] is c

Fiat 500 (color=rose, power=150)
Fiat 500 (color=rose, power=150)


(True, False)

In [48]:
(12, 'rose') == (12, 'rose')

True

In [49]:
(12, 'rose') == (12, 'gris')

False

In [50]:
(12, 'rose') == (12, 'rose', 1250)

False

In [51]:
(12, 'gris') < (12, 'rose') # 12 == 12 then 'gris' < 'rose'

True

In [52]:
(12, 'rose') == [12, 'rose']

False

In [53]:
12 == 12.0

True

In [54]:
12 == "12"

False

In [55]:
x = 12
x.__eq__("12")

NotImplemented

In [56]:
values == 10.0

array([False, False, False, ..., False, False, False])

In [57]:
one_car = cars[0]
same_car = one_car
assert one_car is cars[0]
assert one_car is same_car

In [58]:
# copy with constructor
copy_car = Car(one_car.model, one_car.color, one_car.power)
assert copy_car == one_car
assert copy_car is not one_car

In [59]:
copy_car = copy.copy(one_car)
assert copy_car == one_car
assert copy_car is not one_car

In [60]:
cars[0] < cars[1], \
cars[0] > cars[1]

(False, False)

In [61]:
cars[0] <= cars[1], \
cars[0] >= cars[1]

TypeError: '<=' not supported between instances of 'Car' and 'Car'