# Object Oriented Programming

In [2]:
import pandas as pd
import numpy as np
from decimal import Decimal
import copy

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
from car import Car

## objects and classes from python world

### class 'str'

In [7]:
city = "Toulouse" # object of type (class) str
print(city, type(city), sep=": ")

Toulouse: <class 'str'>


In [8]:
# upper is a method of class str
city.upper()

'TOULOUSE'

In [9]:
city.startswith('Tou')

True

In [10]:
city + ', ville rose'

'Toulouse, ville rose'

In [11]:
# TypeError: can only concatenate str (not "int") to str
# city + 2

In [12]:
city * 10

'ToulouseToulouseToulouseToulouseToulouseToulouseToulouseToulouseToulouseToulouse'

### class 'Decimal' and 'float'

In [14]:
price = Decimal('0.1') # constructor
price, 2*price, 3*price

(Decimal('0.1'), Decimal('0.2'), Decimal('0.3'))

In [15]:
type(price)

decimal.Decimal

In [16]:
price_f = 0.1
price_f, 2*price_f, 3*price_f

(0.1, 0.2, 0.30000000000000004)

In [17]:
type(price_f)

float

### numpy: class 'ndarray'

In [19]:
values = np.random.normal(10, 2.5, 10_000)
matrix = np.random.normal(10, 2.5, (10_000, 10_000))

In [20]:
values

array([10.48005445,  4.19159994,  8.28735986, ..., 10.32536965,
       12.06994493,  6.5486349 ])

In [21]:
for a in values, matrix:
    print(a) # => calls str(a) => calls method ndarray.__str__()
    print("type:", type(a))
    print("shape:", a.shape)
    print("data type:", a.dtype)
    print("data type:", a.flags)
    print("length:", len(a)) # length on 1st dimension => calls method ndarray.__len__()
    print()

[10.48005445  4.19159994  8.28735986 ... 10.32536965 12.06994493
  6.5486349 ]
type: <class 'numpy.ndarray'>
shape: (10000,)
data type: float64
data type:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

length: 10000

[[17.10820409  6.97489027  6.93456726 ... 11.22318575  4.92732857
   8.68526976]
 [13.52956805  6.99250128 10.96418257 ...  9.01460204  7.36118079
  12.14194882]
 [10.36834857  9.42271257 12.07110751 ... 13.29305012 12.41496978
   8.12157594]
 ...
 [12.02545187 14.06190848  4.68727643 ... 11.65318269  8.13538626
   4.16137044]
 [10.46190425  6.87594111  9.90891175 ... 13.37549931 10.99387781
   7.66402697]
 [ 6.30733157 10.68576756 12.30133678 ...  9.683899    6.00908292
  12.36242212]]
type: <class 'numpy.ndarray'>
shape: (10000, 10000)
data type: float64
data type:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

length:

In [22]:
matrix.T.flags # owndata = False => view

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [23]:
matrix.sum()

1000057953.3446584

In [24]:
matrix.sum(axis=1) # by rows

array([ 99753.21134815, 100480.55060751,  99606.10420956, ...,
        99723.13126549, 100283.11039554,  99883.424548  ])

In [25]:
matrix.diagonal()

array([17.10820409,  6.99250128, 12.07110751, ..., 11.65318269,
       10.99387781, 12.36242212])

In [26]:
# ndarray are iterable
list(values[:10])

[10.480054449153794,
 4.191599938356684,
 8.28735985980764,
 11.571995893698897,
 8.77486764462362,
 8.710448617387643,
 5.911153233250668,
 15.469085472821405,
 9.313023193621657,
 8.173617705022014]

In [27]:
values.__iter__

<method-wrapper '__iter__' of numpy.ndarray object at 0x00000121B3D0F9F0>

In [28]:
values[:5] + 1 # calls ndarray.__add__

array([11.48005445,  5.19159994,  9.28735986, 12.57199589,  9.77486764])

In [29]:
# calls int.__add__ with arg values[:5] => returns NotImplemented
# calls ndarray.__radd__
1 + values[:5] 

array([11.48005445,  5.19159994,  9.28735986, 12.57199589,  9.77486764])

In [30]:
x = 1
x.__add__(values[:5])

NotImplemented

In [31]:
values[:5].__radd__(1)

array([11.48005445,  5.19159994,  9.28735986, 12.57199589,  9.77486764])

In [32]:
values.shape

(10000,)

In [33]:
values.shape = (100, 100)
values.shape

(100, 100)

In [34]:
values

array([[10.48005445,  4.19159994,  8.28735986, ..., 12.31523965,
        13.24068039,  9.78433089],
       [11.08891654, 11.55943041, 11.88553756, ..., 10.5612844 ,
        11.9179115 ,  6.49879403],
       [13.20091195, 10.94021   ,  8.83025443, ..., 11.56192953,
        15.13192044, 13.49893   ],
       ...,
       [11.59556688,  7.74789668,  9.08513079, ..., 12.98152419,
        14.45625279, 13.01914399],
       [ 9.11524789,  9.98829507, 10.20428099, ..., 11.23891511,
        16.56834206,  8.38756212],
       [11.37747186, 12.03234049,  9.29488055, ..., 10.32536965,
        12.06994493,  6.5486349 ]])

In [35]:
# ValueError: cannot reshape array of size 10000 into shape (1000,1000)
# values.shape = (1000, 1000)

## custom class 'Car'

In [37]:
Car?

Init signature: Car(model: str, color: str | None = None, power: int | None = None)
Docstring:     
class representing a car with its model, power and color

Example:
    car = Car(model='Fiat 500', color='rose', power=150)
File:           c:\users\matth\documents\formation\python\stage20240722perf\car.py
Type:           type
Subclasses:     

In [38]:
c = Car('Fiat 500') # calls constructor __init__(...)
print(c) # calls str()
c # calls repr()

Fiat 500 (color=None, power=None)


Car(model=Fiat 500, color=None, power=None)

In [39]:
c.model

'Fiat 500'

In [40]:
c.color = 'rose'
c.color

'rose'

In [41]:
# AttributeError: 'Car' object has no attribute 'kilometer'
# c.kilometer
# c.kilometer = 100_000 # ok if no slots else AttributeError: 'Car' object has no attribute 'kilometer'
# c.kilometer

In [42]:
c2 = Car('Super 5')
# AttributeError: 'Car' object has no attribute 'kilometer'
# c2.kilometer

In [43]:
dir(c)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 'color',
 'model',
 'power']

In [44]:
c.__class__ # or type(c)

car.Car

In [45]:
c.__module__

'car'

In [46]:
cars = [
    Car(model="Fiat 500", color="rose", power=150),
    Car(model="Super 5", color="gris", power=65),
    Car(model="Ferrari F40", color="rouge", power=400),
]

In [47]:
# fonction anonyme
# anonymouse function
# lambda function
# Ex:    lambda car: car.power
# en Java: car -> car.power
# en Javascript, C#:   car => car.power
cars.sort(key=lambda car: car.power, reverse=True)
cars

[Car(model=Ferrari F40, color=rouge, power=400),
 Car(model=Fiat 500, color=rose, power=150),
 Car(model=Super 5, color=gris, power=65)]

In [48]:
# TypeError: '<' not supported between instances of 'Car' and 'Car'
# cars.sort()

In [49]:
c = Car(model="Fiat 500", color="rose", power=150)
c in cars

True

In [50]:
print(cars[0])
print(c)
cars[0] == c, cars[0] is c

Ferrari F40 (color=rouge, power=400)
Fiat 500 (color=rose, power=150)


(False, False)

In [51]:
print(cars[1])
print(c)
cars[1] == c, cars[1] is c

Fiat 500 (color=rose, power=150)
Fiat 500 (color=rose, power=150)


(True, False)

In [52]:
(12, 'rose') == (12, 'rose')

True

In [53]:
(12, 'rose') == (12, 'gris')

False

In [54]:
(12, 'rose') == (12, 'rose', 1250)

False

In [55]:
(12, 'gris') < (12, 'rose') # 12 == 12 then 'gris' < 'rose'

True

In [56]:
(12, 'rose') == [12, 'rose']

False

In [57]:
12 == 12.0

True

In [58]:
12 == "12"

False

In [59]:
x = 12
x.__eq__("12")

NotImplemented

In [60]:
values == 10.0

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [61]:
one_car = cars[0]
same_car = one_car
assert one_car is cars[0]
assert one_car is same_car

In [62]:
# copy with constructor
copy_car = Car(one_car.model, one_car.color, one_car.power)
assert copy_car == one_car
assert copy_car is not one_car

In [63]:
copy_car = copy.copy(one_car)
assert copy_car == one_car
assert copy_car is not one_car

In [64]:
cars[0] < cars[1], \
cars[0] > cars[1]

(False, True)

In [65]:
cars[0] <= cars[1], \
cars[0] >= cars[1]

(False, True)